config/routes.rb
Rails.application.routes.draw do
  get 'conversations/index'
  get 'conversations/show/:id', to: 'conversations#show', as: 'show_conversation' 
  get '/welcome/privacy_policy', to: 'welcome#privacy_policy', as: 'privacy_policy'
  get 'welcome/terms_of_service', to: 'welcome#terms_of_service', as: 'terms_of_service'
  resources :microposts, only: [:show, :create, :destroy]
  get 'microposts/show_more/:id', to: 'microposts#show_more', as: 'show_more_microposts'
  patch 'microposts/edit', to: 'microposts#edit', as: 'micropost_edit'
  patch 'microposts/:id/toggle_privacy', to: 'microposts#privacy', as: 'micropost_privacy'
  post 'like_comment/:id', to: 'likes#toggle_comment', as: 'toggle_comment_like'
  post 'like_micropost/:id', to: 'likes#toggle_micropost', as: 'toggle_micropost_like'

  namespace :users do 
    get 'profile/:id', to: 'profiles#show', as: 'profile'
    post 'change_avatar', to: 'avatars#create', as: 'create_avatar'
    get 'avatar', to: 'avatars#new', as: 'get_avatar_form'
  end

  resources :comments
  get 'users/profile/:id/albums', to: 'albums#index', as: 'user_albums'
  get 'users/profile/:user_id/albums/:id', to: 'albums#show', as: 'show_album'
  post 'albums', to: 'albums#create', as: 'create_album'
  delete 'album/:id', to: 'albums#destroy', as: 'destroy_album'
  post 'pictures', to: 'pictures#create', as: 'upload_pictures'
  patch 'pictures/:id', to: 'pictures#edit', as: 'edit_picture_caption'
  delete 'pictures/:id', to: 'pictures#destroy', as: 'destroy_picture'
  get 'search_user', to: 'searches#search_user'
  get 'short_search', to: 'searches#short_search'
  get 'conversation/load_more_messages', to: 'conversations#more_messages'


  devise_for :users, skip:[:sessions, :registrations], controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
   devise_scope :user do
     get 'users/sign_in', to: 'users/sessions_or_registrations#new', as: 'new_user_session'
     post '/users/sign_in', to: 'users/sessions#create', as: 'user_session'
     delete 'users/sign_out', to: 'users/sessions#destroy', as: 'destroy_user_session'
     patch 'users', to: 'users/registrations#update'
     put 'users', to: 'users/registrations#update'
     delete 'users', to: 'users/registrations#destroy'
     get 'users/sign_up', to: 'users/sessions_or_registrations#new', as: 'new_user_registration'
     get 'users/sign_up', to: 'users/sessions_or_registrations#new', as: 'new_registration'
     post 'users', to: 'users/registrations#create', as: 'user_registration'

   end

  root 'users/sessions_or_registrations#new'
  
  mount ActionCable.server => '/cable'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  has_many :comment_likes, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_user, only: :create
  before_action :correct_user, only: :destroy
  before_action :no_likes, only: :create

  def create
    @comment = Comment.new(safe_params)
    respond_to do |format|
      if @comment.save
        format.html { render partial: 'comments/comment', locals: {comment: @comment}, status: :created }
        format.js {}
      else
        format.html { render @comment.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  def destroy
    respond_to do |format|
      if !@comment.blank? && @comment.destroy
        format.html { head :ok }
        format.js {}
      else
        format.html { head :unprocessable_entity }
        format.js {}
      end
    end
  end

  private
    def safe_params
      params['comment']['user_id'] = current_user.id
      params.require(:comment).permit(:micropost_id, :context, :user_id)
    end

    def no_likes
      @comment_likes = false
    end

    def correct_user
      @comment = Comment.where('user_id=?', "#{current_user.id}").find_by(id: params[:id])
    end

    def find_user
      @users = [] << current_user
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class='comment-container data-comment-id=<%= "#{comment.id}" %>'>
  <div class='row'>
    <%= image_tag user_thumb(comment), class: 'comment-profile-icon profile-icon ' %>
    <%= profile_link(comment.user_id, 'user-profile-link') %>

    <span class='delete-comment pull-right'>
      <% if comment.user_id == current_user.id %>
        <%= link_to comment, class: 'delete-comment', method: :delete, remote: true do %>
          <span class='glyphicon glyphicon-remove'></span>
        <% end %>
      <% end %>
    </span>

    <span><%= comment.context %></span>

  </div>

  <div class='row'>
      <ul class='list-inline comment-footer'>

        <li>
          <%= link_to toggle_comment_like_path(comment.id), class: 'comment-like-btn', remote: true, method: :post do -%>
            <span class='glyphicon glyphicon-thumbs-up <%= 'active' if @comment_likes && @comment_likes.include?(comment.id) -%>'></span>
            <span class='thumbs count'><%= comment.comment_likes_count %></span>
          <% end %>
        </li>

      </ul>

      <span class='date-time-comment pull-right'>
        <%= date_and_time(comment) %>
      </span>

  </div>
  
</div>

app/views/comments/_comment_form.html.erb
<div class='comment-form-container'>
<%= form_tag({controller: '/comments', action:'create'}, remote: true, method: 'post', class: 'comment-form') do -%>
  <%= hidden_field_tag 'comment[micropost_id]', micropost_id %>
  <%= text_area_tag 'comment[context]', '', class: 'comment-text-area', placeholder: 'Comment here...' %>
  <%= submit_tag 'Comment', class: 'comment-btn post-btn btn btn-primary' %>
<% end %>
</div>