config/routes.rb
Rails.application.routes.draw do
  get 'conversations/index'
  get 'conversations/show/:id', to: 'conversations#show', as: 'show_conversation' 
  get '/welcome/privacy_policy', to: 'welcome#privacy_policy', as: 'privacy_policy'
  get 'welcome/terms_of_service', to: 'welcome#terms_of_service', as: 'terms_of_service'
  resources :microposts, only: [:show, :create, :destroy]
  get 'microposts/show_more/:id', to: 'microposts#show_more', as: 'show_more_microposts'
  patch 'microposts/edit', to: 'microposts#edit', as: 'micropost_edit'
  patch 'microposts/:id/toggle_privacy', to: 'microposts#privacy', as: 'micropost_privacy'
  post 'like_comment/:id', to: 'likes#toggle_comment', as: 'toggle_comment_like'
  post 'like_micropost/:id', to: 'likes#toggle_micropost', as: 'toggle_micropost_like'

  namespace :users do 
    get 'profile/:id', to: 'profiles#show', as: 'profile'
    post 'change_avatar', to: 'avatars#create', as: 'create_avatar'
    get 'avatar', to: 'avatars#new', as: 'get_avatar_form'
  end

  resources :comments
  get 'users/profile/:id/albums', to: 'albums#index', as: 'user_albums'
  get 'users/profile/:user_id/albums/:id', to: 'albums#show', as: 'show_album'
  post 'albums', to: 'albums#create', as: 'create_album'
  delete 'album/:id', to: 'albums#destroy', as: 'destroy_album'
  post 'pictures', to: 'pictures#create', as: 'upload_pictures'
  patch 'pictures/:id', to: 'pictures#edit', as: 'edit_picture_caption'
  delete 'pictures/:id', to: 'pictures#destroy', as: 'destroy_picture'
  get 'search_user', to: 'searches#search_user'
  get 'short_search', to: 'searches#short_search'
  get 'conversation/load_more_messages', to: 'conversations#more_messages'


  devise_for :users, skip:[:sessions, :registrations], controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
   devise_scope :user do
     get 'users/sign_in', to: 'users/sessions_or_registrations#new', as: 'new_user_session'
     post '/users/sign_in', to: 'users/sessions#create', as: 'user_session'
     delete 'users/sign_out', to: 'users/sessions#destroy', as: 'destroy_user_session'
     patch 'users', to: 'users/registrations#update'
     put 'users', to: 'users/registrations#update'
     delete 'users', to: 'users/registrations#destroy'
     get 'users/sign_up', to: 'users/sessions_or_registrations#new', as: 'new_user_registration'
     get 'users/sign_up', to: 'users/sessions_or_registrations#new', as: 'new_registration'
     post 'users', to: 'users/registrations#create', as: 'user_registration'

   end

  root 'users/sessions_or_registrations#new'
  
  mount ActionCable.server => '/cable'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  has_many :comments, dependent: :destroy
  validates :context, presence: true, length: { minimum: 1, maximum: 300 }
  default_scope -> { order(created_at: :desc) }
  has_many :micropost_likes, dependent: :destroy


end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :show_more
  before_action :correct_user, only: :destroy

  
  def create
    @micropost = Micropost.new(safe_params)

    respond_to do |format|
      if @micropost.save
        @users = find_micropost_participants
        format.html { render partial: 'microposts/micropost', locals: {micropost: @micropost}, status: :created }
        format.js {}
      else
        format.html { render html: @micropost.errors, status: :unproccessable_entity }
      end
    end
  end

  def edit
    micropost = correct_user_for_edit

    respond_to do |format|
      if micropost && micropost.update({ context: safe_edit_params[:context] })
        format.html { head :accepted }
      else
        format.html { head :unauthorized }
      end
    end
  end

  def destroy
    respond_to do |format|
      if !@micropost.blank? && @micropost.destroy
        format.html { head :ok}
      else
        format.html { head :unproccessable_entity }
      end
    end
  end

  def privacy
    current_user
    micropost = Micropost.find_by(id: params[:id])
    micropost.toggle(:private) if current_user.id == micropost.author_id || current_user.id == micropost.receiver_id
    respond_to do |format|
      if micropost.save
        format.html { head :ok }
        format.js
      else
        format.html { head :unprocessable_entity }
        format.js
      end
    end
  end

  def show_more
    @microposts = current_user.microposts.where('id<?', params[:id]).includes(:comments).take(10)
    @users = User.select(:id, :name).where(id: user_ids(@microposts))

    respond_to do |format|
      if @microposts && @users
        format.html { render partial: 'microposts/micropost', collection: @microposts, status: :ok }
      else
        format.html { @microposts.errors }
      end
    end
  end

  private

    def correct_user
      @micropost = Micropost.where('author_id=? OR receiver_id=?', "#{current_user.id}", "#{current_user.id}").find_by(id: params[:id])
    end

    def correct_user_for_edit
      @micropost = Micropost.where('author_id=?', "#{current_user.id}").find_by(id: safe_edit_params[:id])
    end


    def find_micropost_participants
      User.where(id: [@micropost.author_id, @micropost.receiver_id])
    end

    def safe_params
      params.require(:micropost).permit(:context, :author_id, :receiver_id)
    end

    def safe_edit_params
      params.require(:micropost).permit(:context, :id)
    end
    
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<div class='col-xs-12 col-md-8 micropost-container pull-right'>
  <div class="col-xs-12 col-md-5 micropost-div">
    <div class= 'row micropost-header micropost'>

      <% if (micropost.author_id == current_user.id) %>

        <%= link_to micropost_privacy_path(micropost), remote: true, class: 'privacy-btn', method: :patch do %> 
          <span class='glyphicon col-md-1 micropost-header-icon glyphicon-eye-open <%= 'active' if micropost.private -%>'></span>
        <% end %>
        <%= link_to '#', class: 'edit-micropost-btn' do %>
          <span class='glyphicon col-md-1 micropost-header-icon glyphicon-pencil'></span>
        <% end %>

      <% end %>

      <span class='micropost-header-text'>
        <%= micropost.author_id == micropost.receiver_id ? profile_link(micropost.author_id) :  micropost_sender_receiver_html(micropost)-%>
        </span>

        <% if ((micropost.author_id == current_user.id) || (micropost.receiver_id == current_user.id)) %>
          <%= link_to micropost, class: 'delete-micropost', method: :delete, remote: true do %>
            <span class='glyphicon col-md-1 micropost-header-icon glyphicon-remove pull-right' data-micropost-id=<%= "#{micropost.id}"%>></span>
          <% end %>
        <% end %>

    </div>
    <div class='row border-bottom'>
      <%= image_tag user_thumb(micropost), alt: 'Profile photo', height: '30', class: 'micropost-profile-icon profile-icon' -%>
      <%= content_tag :div, id: "micropost-#{micropost.id}", class: 'micropost-content' do -%>
        <%= content_tag :p, "#{micropost.context}", class: 'micropost-paragraf' -%>
        <%= (render partial: 'microposts/micropost_edit_form', locals: {micropost: micropost}) if micropost.author_id == current_user.id -%>
      <% end %>

      <div class='row'>
        <ul class='list-inline micropost-footer'>

          <li>
            <%= link_to toggle_micropost_like_path(micropost.id), class: 'micropost-like-btn', method: 'post', remote: true do -%>
              <span class='glyphicon glyphicon-thumbs-up <%= 'active' if @micropost_likes && @micropost_likes.include?(micropost.id) -%>'></span>
              <span class='thumbs count'><%= micropost.micropost_likes_count -%></span>
            <% end %>
          </li>

        </ul>

        <span class='date-time pull-right'>
          <%= date_and_time(micropost) %>
        </span>

      </div>
    </div>

    <div class='row comment-row'>
      <%= render partial: 'comments/comment', collection: (@comments = micropost.comments) %>
    </div>
      <div class='row'>
        <%= render partial: 'comments/comment_form', locals: {micropost_id: micropost.id} %>
      </div>

    <a href='#' class='row show-more' data-show='false'>Show more</a>
  </div>
</div>

app/views/microposts/_micropost_edit_form.html.erb
<%= form_tag(micropost_edit_path, remote: true, method: 'patch', class: 'micropost-edit-form') do -%>
  <%= hidden_field_tag 'micropost[id]', micropost.id, {class: 'micropost-id'} %>
  <%= text_area_tag 'micropost[context]', '', class: 'micropost-text-area', size: '25x3' -%>
  <%= submit_tag 'Change', class: 'edit-submit-btn btn btn-danger pull-right' -%>
  <%= button_tag 'Cancel', class: 'edit-cancel-btn btn btn-primary pull-right', type: 'button' -%>
<% end %>

app/views/microposts/_micropost_form.html.erb
<div class='col-xs-12 col-md-8 micropost-container pull-right'>
  <div class="col-xs-12 col-md-5 micropost-div">
    <%= form_tag({controller: '/microposts', action:'create'}, remote: true, method: 'post', id: 'micropost-form') do -%>
      <%= hidden_field_tag 'micropost[author_id]', current_user.id %>
      <%= hidden_field_tag 'micropost[receiver_id]', params[:id] %>    
      <div class= 'row micropost-header'>
        <span class='glyphicon col-md-1 micropost-header-icon glyphicon-camera'></span>
        <span class='glyphicon col-md-1 micropost-header-icon glyphicon-picture'></span>
        <span class='glyphicon col-md-1 micropost-header-icon glyphicon-map-marker'></span>
      </div>
      <div class='row border-bottom'>
        <%= image_tag current_user.avatar.url(:thumb), alt: 'Profile photo', height: '30', id: 'form-profile-icon', class: 'micropost-profile-icon profile-icon' -%>
        <%= text_area_tag 'micropost[context]', '', class: 'micropost-text-area', size: '25x3', placeholder: 'Write something...' -%>
      </div>
      <div class='row'>
        <%= submit_tag 'Post', class: 'post-btn btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/microposts/trendline.html.erb
<% provide :title, "Trendline" %>
<h1>Ovo je trendline sada</h1>