config/routes.rb
Rails.application.routes.draw do
  get 'conversations/index'
  get 'conversations/show/:id', to: 'conversations#show', as: 'show_conversation' 
  get '/welcome/privacy_policy', to: 'welcome#privacy_policy', as: 'privacy_policy'
  get 'welcome/terms_of_service', to: 'welcome#terms_of_service', as: 'terms_of_service'
  resources :microposts, only: [:show, :create, :destroy]
  get 'microposts/show_more/:id', to: 'microposts#show_more', as: 'show_more_microposts'
  patch 'microposts/edit', to: 'microposts#edit', as: 'micropost_edit'
  patch 'microposts/:id/toggle_privacy', to: 'microposts#privacy', as: 'micropost_privacy'
  post 'like_comment/:id', to: 'likes#toggle_comment', as: 'toggle_comment_like'
  post 'like_micropost/:id', to: 'likes#toggle_micropost', as: 'toggle_micropost_like'

  namespace :users do 
    get 'profile/:id', to: 'profiles#show', as: 'profile'
    post 'change_avatar', to: 'avatars#create', as: 'create_avatar'
    get 'avatar', to: 'avatars#new', as: 'get_avatar_form'
  end

  resources :comments
  get 'users/profile/:id/albums', to: 'albums#index', as: 'user_albums'
  get 'users/profile/:user_id/albums/:id', to: 'albums#show', as: 'show_album'
  post 'albums', to: 'albums#create', as: 'create_album'
  delete 'album/:id', to: 'albums#destroy', as: 'destroy_album'
  post 'pictures', to: 'pictures#create', as: 'upload_pictures'
  patch 'pictures/:id', to: 'pictures#edit', as: 'edit_picture_caption'
  delete 'pictures/:id', to: 'pictures#destroy', as: 'destroy_picture'
  get 'search_user', to: 'searches#search_user'
  get 'short_search', to: 'searches#short_search'
  get 'conversation/load_more_messages', to: 'conversations#more_messages'


  devise_for :users, skip:[:sessions, :registrations], controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
   devise_scope :user do
     get 'users/sign_in', to: 'users/sessions_or_registrations#new', as: 'new_user_session'
     post '/users/sign_in', to: 'users/sessions#create', as: 'user_session'
     delete 'users/sign_out', to: 'users/sessions#destroy', as: 'destroy_user_session'
     patch 'users', to: 'users/registrations#update'
     put 'users', to: 'users/registrations#update'
     delete 'users', to: 'users/registrations#destroy'
     get 'users/sign_up', to: 'users/sessions_or_registrations#new', as: 'new_user_registration'
     get 'users/sign_up', to: 'users/sessions_or_registrations#new', as: 'new_registration'
     post 'users', to: 'users/registrations#create', as: 'user_registration'

   end

  root 'users/sessions_or_registrations#new'
  
  mount ActionCable.server => '/cable'
end

app/views/layouts/_alert.html.erb
<div class='col-md-4 col-lg-4 col-xs-12 col-sm-12 alert alert-danger text-center'>
  <p class='alert'><%= alert %></p>
</div>

app/views/layouts/_chat_container.html.erb
<% if user_signed_in? %>
  <div class='chat-container' data-current-user=<%= current_user.id %>></div>
<% end %>

app/views/layouts/_devise_errors.html.erb
<div class='row messages-row'>
  <div class='col-md-4 col-lg-4 col-xs-12 col-sm-12 alert alert-danger text-center'>
    <p class='alert'><%= devise_error_messages! %></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
    <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to  '#', class: 'navbar-brand', id: 'brand' do %>
      <%= image_tag 'bug_white.png', id: 'logo-icon' %>
      <%= content_tag :span, 'Oosh', id: 'logo-name' %> 
    <% end %>

  </div>
    
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
      
      <%= form_tag({ action: 'search_user', controller: '/searches' }, method: :get, class: 'navbar-form navbar-left') do -%>
        <div class="form-group">
          <%= search_field_tag( 'search-field', nil, name: 'search-query', class: 'form-control', placeholder: 'Search', type:'text', autocomplete: 'off') -%>
          <div id='query-results'></div>
        </div>
        <%= submit_tag('Submit', class:'btn btn-default', id: 'submit-search') -%>
      <% end %>

    <% end %>

    <div>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li><%= link_to users_profile_path(current_user), data: { turbolinks: false }, title:"#{current_user.name} profile" do -%>
            <%= image_tag(current_user.avatar.url(:thumb), height:"30", class: "profile-icon header-profile-icon") + 
            content_tag(:div, current_user.name.split(" ")[0], class: "profile-link")  -%><%end-%></li>
          <li><%= link_to users_profile_path(current_user), data: { turbolinks: false }, title: "Messages", id:'open-chatbox' do -%>
            <%= content_tag(:span, nil, class: "glyphicon header-icon glyphicon-envelope") -%><%end-%></li>
          <li><%= link_to users_profile_path(current_user), title: "Notifications" do -%>
            <%= content_tag(:span, nil, {class: "glyphicon header-icon glyphicon-exclamation-sign"}) -%><%end-%></li>
          <li><%= link_to destroy_user_session_path, id: 'current-user', method: :delete, title: 'Log Out' do -%>
            <%= content_tag(:span, nil, {class: "spin-forward header-icon glyphicon glyphicon-minus-sign"}) -%><%end-%></li>

          <li class="dropdown">
            <a href="#" id="cog" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon header-icon glyphicon-cog"></span> <span id="caret" class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>

        <% else %>

          <li><%= link_to new_user_session_path, title:'Login' do -%><%= content_tag(:span, nil, {class: "glyphicon header-icon glyphicon-user"}) -%><%end-%>  </li>

        <% end -%>
      </ul>

    </div>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_messages.html.erb
<div class='row messages-row'>
      <% if notice %>
        <%= render 'layouts/notice' %>
      <% end %> 
      <% if alert %>
        <%= render 'layouts/alert' %>
      <% end %>
</div>

app/views/layouts/_notice.html.erb
<div class='col-md-4 col-lg-4 col-xs-12 col-sm-12 alert alert-success text-center'>
  <p class='notice'><%= notice %></p>
</div>

app/views/layouts/_short_search.html.erb
<ul class='search-list-short'>
  <% if users.any? %>
    <% users.each do |user| %>
      <li>
        <%= link_to users_profile_url(user.id) do -%>
          <%= image_tag user.avatar.url(:thumb), class: 'search-user-img profile-icon' -%>
          <span><%= user.name %></span>
        <% end %>
        <%= link_to show_conversation_path(user), remote: true, class: 'search-icons pull-right' do %>
          <span class='glyphicon glyphicon-heart-empty'></span>
        <% end %>
        <%= link_to show_conversation_path(user), data:{ 'user-id': user.id }, remote: true, class: 'new-personal-message search-icons pull-right' do %>
          <span class='glyphicon glyphicon-envelope'></span>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <li>
      <span>No users found.<span>
    </li>
  <% end %>
</ul>

app/views/layouts/_sidebar.html.erb
<div id="wrapper" class="sidebar-invisible">
 <div id="sidebar-wrapper">
    <div id="sidebar-button-wrapper"><div class="vertical-center"><span class="glyphicon glyphicon-chevron-left"></span></div></div>
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="#">
          Something
        </a>
      </li>
      <li>
        <a href="#">Something else</a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= page_title(yield(:title)) %></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' -%>

    <% if user_signed_in? %>
      <%= render 'layouts/sidebar' -%>
    <% end %>

    <div class="container-fluid">
      <% if alert || notice %>
        <%= render 'layouts/messages' %>
      <% end %>

      <%= yield %>
    </div>

    <%= render 'layouts/chat_container' -%>

  </body>

  <% if Rails.env.development? %>
    <div class="col-md-12">
      <div id='params-window'><%= debug(params) %></div>
      <div id='console-window'><%= console %></div>
    </div>
  <% end %>
</html>